ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: chmod +x /workspace/gitpod_simplejupyter/run.sh && /workspace/gitpod_simplejupyter/run.sh
  command: cp -r /workspace/gitpod_simplejupyter/.jupyter /home/gitpod/ && jupyter notebook
