ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/gitpod_ICSharpCore/run.sh
  command: cp -r /workspace/gitpod_ICSharpCore/.jupyter /home/gitpod/
